const LOAD_SERVER_DATA = "LOAD_SERVER_DATA";
const IS_LOADING = "IS_LOADING";
const LOAD_ERROR = "ERROR_LOAD";
const LOAD_SUCCESS = "LOAD_SUCCESS";
const WRITE_TO_STORE = "WRITE_TO_STORE";
const LOAD_FROM_LOCALSTORE = "LOAD_FROM_LOCALSTORE";
const WRITE_WISH_LIST = "WRITE_WISH_LIST";
const WRITE_CART = "WRITE_CART";

export default {
    LOAD_SERVER_DATA,
    IS_LOADING,
    LOAD_ERROR,
    LOAD_SUCCESS,
    WRITE_TO_STORE,
    LOAD_FROM_LOCALSTORE,
    WRITE_WISH_LIST,
    WRITE_CART,
}
;
